# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a08bb75c21fb6cd00372428b00278618d423cd20e091e351fd82c8863f0b7aede9ca63dbf71d241c87c0e724465bcef4e2677256dd53294703f568935b43abb

test:
  secret_key_base: 98196410debbb6c8ecd80d5c077671561251e47dbb0327419f9055b3423a24b37309301b9e3bd808b6e3bf347aa369e22f8d49a76017647db6a73b38458e6eda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
